import type { SdfPrim } from "./sculpt";
/**
 * Voxel models for generated creatures and objects. A model is made of parts
 * (body, tail, fins, wings…); each part is a small 3D grid of palette
 * colours that can move around its pivot for animation. Generated by code
 * (docs/standards/art-and-3d-assets.md: procedural first), deterministic, so
 * server and clients build identical models from the same spec.
 */

/** How a surface takes the light: matte (default), gloss (shiny), metal (shiny and tinted), glow (lit from within). */
export type Finish = "matte" | "gloss" | "metal" | "glow";
export const FINISHES: Finish[] = ["matte", "gloss", "metal", "glow"];

export class VoxelGrid {
  readonly data: Uint8Array;
  /** Index 0 is empty. */
  readonly palette: string[] = [""];
  /** Finish of each palette entry (index into FINISHES), parallel to `palette`. */
  readonly finish: number[] = [0];

  constructor(readonly w: number, readonly h: number, readonly d: number) {
    this.data = new Uint8Array(w * h * d);
  }

  /** Palette index for a colour (added if new). */
  color(hex: string, finish = 0): number {
    for (let i = 1; i < this.palette.length; i++) if (this.palette[i] === hex && this.finish[i] === finish) return i;
    if (this.palette.length >= 255) throw new Error("too many colours in one part");
    this.palette.push(hex);
    this.finish.push(finish);
    return this.palette.length - 1;
  }

  inside(x: number, y: number, z: number): boolean {
    return x >= 0 && y >= 0 && z >= 0 && x < this.w && y < this.h && z < this.d;
  }

  get(x: number, y: number, z: number): number {
    return this.inside(x, y, z) ? this.data[(y * this.d + z) * this.w + x] : 0;
  }

  set(x: number, y: number, z: number, c: number): void {
    if (this.inside(x, y, z)) this.data[(y * this.d + z) * this.w + x] = c;
  }

  /** Fill an ellipsoid (voxel centres inside it). `pick` can vary the colour per voxel. */
  ellipsoid(cx: number, cy: number, cz: number, rx: number, ry: number, rz: number, c: number | ((x: number, y: number, z: number) => number)): void {
    for (let y = Math.floor(cy - ry); y <= Math.ceil(cy + ry); y++)
      for (let z = Math.floor(cz - rz); z <= Math.ceil(cz + rz); z++)
        for (let x = Math.floor(cx - rx); x <= Math.ceil(cx + rx); x++) {
          const dx = (x + 0.5 - cx) / rx, dy = (y + 0.5 - cy) / ry, dz = (z + 0.5 - cz) / rz;
          if (dx * dx + dy * dy + dz * dz <= 1) this.set(x, y, z, typeof c === "number" ? c : c(x, y, z));
        }
  }

  box(x0: number, y0: number, z0: number, x1: number, y1: number, z1: number, c: number): void {
    for (let y = y0; y <= y1; y++) for (let z = z0; z <= z1; z++) for (let x = x0; x <= x1; x++) this.set(x, y, z, c);
  }

  /** Recolour solid voxels matching a test. */
  paint(test: (x: number, y: number, z: number, c: number) => boolean, c: number): void {
    for (let y = 0; y < this.h; y++)
      for (let z = 0; z < this.d; z++)
        for (let x = 0; x < this.w; x++) {
          const cur = this.get(x, y, z);
          if (cur && test(x, y, z, cur)) this.set(x, y, z, c);
        }
  }

  count(): number {
    let n = 0;
    for (const v of this.data) if (v) n++;
    return n;
  }
}

export interface VoxelPart {
  name: string;
  grid: VoxelGrid;
  /** Where the grid's (0,0,0) corner sits, in voxels, relative to the model origin (feet centre). */
  origin: [number, number, number];
  /** Rotation pivot in voxels, relative to the model origin. */
  pivot: [number, number, number];
  /** Animation role: tail sways, fins/wings flap, legs walk, head looks. */
  anim?: "tail" | "finL" | "finR" | "wingL" | "wingR" | "legL" | "legR" | "armL" | "armR" | "head" | "jaw" | "body" | "neck" | "earL" | "earR" | "antenna" | "tentacle" | "lid";
  /** For models written as shapes: the primitives as distance fields, in this grid's coordinates (the sculpted style). */
  sdf?: SdfPrim[];
  /** A segment of a chain (a tail split along its tube): the part it hangs from, by index, and its place in the chain. */
  parent?: number;
  chain?: number;
}

export interface VoxelModel {
  /** Blocks per voxel (1/16 for small props, coarser for big things). */
  voxelSize: number;
  parts: VoxelPart[];
}

export interface MeshData {
  positions: Float32Array;
  normals: Float32Array;
  /** sRGB colours, 0..1. */
  colors: Float32Array;
  indices: Uint32Array;
  quads: number;
  /** Finish of each triangle (index into FINISHES), when any isn't matte. */
  finishes?: Uint8Array;
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16) / 255, parseInt(h.slice(2, 4), 16) / 255, parseInt(h.slice(4, 6), 16) / 255];
}

/**
 * Greedy meshing: merge same-coloured visible faces into large rectangles,
 * so a big cloud is a few hundred quads, not tens of thousands.
 * Positions are in voxel units relative to the grid's corner.
 */
export function greedyMesh(g: VoxelGrid): MeshData {
  const pos: number[] = [], nor: number[] = [], col: number[] = [], idx: number[] = [], fin: number[] = [];
  const dims = [g.w, g.h, g.d];
  const rgb = g.palette.map((c) => (c ? hexToRgb(c) : [0, 0, 0] as [number, number, number]));
  const at = (p: number[]) => g.get(p[0], p[1], p[2]);
  let quads = 0;
  for (let d = 0; d < 3; d++) {
    const u = (d + 1) % 3, v = (d + 2) % 3;
    const x = [0, 0, 0], q = [0, 0, 0];
    q[d] = 1;
    const mask = new Int32Array(dims[u] * dims[v]);
    for (x[d] = -1; x[d] < dims[d];) {
      // Build the mask of faces between slice x[d] and x[d]+1. Positive = face pointing +d, negative = -d.
      let n = 0;
      for (x[v] = 0; x[v] < dims[v]; x[v]++)
        for (x[u] = 0; x[u] < dims[u]; x[u]++, n++) {
          const a = x[d] >= 0 ? at(x) : 0;
          const b = x[d] < dims[d] - 1 ? at([x[0] + q[0], x[1] + q[1], x[2] + q[2]]) : 0;
          mask[n] = a && !b ? a : !a && b ? -b : 0;
        }
      x[d]++;
      n = 0;
      for (let j = 0; j < dims[v]; j++)
        for (let i = 0; i < dims[u];) {
          const c = mask[n];
          if (!c) { i++; n++; continue; }
          let w = 1;
          while (i + w < dims[u] && mask[n + w] === c) w++;
          let h = 1;
          outer: for (; j + h < dims[v]; h++)
            for (let k = 0; k < w; k++) if (mask[n + k + h * dims[u]] !== c) break outer;
          x[u] = i; x[v] = j;
          const du = [0, 0, 0], dv = [0, 0, 0];
          du[u] = w; dv[v] = h;
          const color = rgb[Math.abs(c)];
          const normal = [0, 0, 0];
          normal[d] = c > 0 ? 1 : -1;
          const b = pos.length / 3;
          const corners = [
            [x[0], x[1], x[2]],
            [x[0] + du[0], x[1] + du[1], x[2] + du[2]],
            [x[0] + du[0] + dv[0], x[1] + du[1] + dv[1], x[2] + du[2] + dv[2]],
            [x[0] + dv[0], x[1] + dv[1], x[2] + dv[2]],
          ];
          for (const p of corners) { pos.push(p[0], p[1], p[2]); nor.push(normal[0], normal[1], normal[2]); col.push(color[0], color[1], color[2]); }
          // Winding so the face points along its normal.
          if (c > 0) idx.push(b, b + 1, b + 2, b, b + 2, b + 3);
          else idx.push(b, b + 2, b + 1, b, b + 3, b + 2);
          const f = g.finish[Math.abs(c)] ?? 0;
          fin.push(f, f);
          quads++;
          for (let l = 0; l < h; l++) for (let k = 0; k < w; k++) mask[n + k + l * dims[u]] = 0;
          i += w; n += w;
        }
    }
  }
  return { positions: new Float32Array(pos), normals: new Float32Array(nor), colors: new Float32Array(col), indices: new Uint32Array(idx), quads, ...(fin.some((f) => f) ? { finishes: Uint8Array.from(fin) } : {}) };
}

export interface ModelStats {
  /** Size in blocks (x = width, y = height, z = length). */
  size: [number, number, number];
  triangles: number;
  voxels: number;
  colors: string[];
}

/** Longest side of the filled voxels, in blocks (cheap: no meshing). */
export function modelLength(m: VoxelModel): number {
  let min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
  for (const p of m.parts) {
    const g = p.grid;
    for (let y = 0; y < g.h; y++)
      for (let z = 0; z < g.d; z++)
        for (let x = 0; x < g.w; x++) {
          if (!g.data[(y * g.d + z) * g.w + x]) continue;
          const v = [p.origin[0] + x, p.origin[1] + y, p.origin[2] + z];
          for (let i = 0; i < 3; i++) { if (v[i] < min[i]) min[i] = v[i]; if (v[i] + 1 > max[i]) max[i] = v[i] + 1; }
        }
  }
  return Math.max(max[0] - min[0], max[1] - min[1], max[2] - min[2]) * m.voxelSize;
}

export function modelStats(m: VoxelModel): ModelStats {
  let minX = Infinity, minY = Infinity, minZ = Infinity, maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
  let tris = 0, voxels = 0;
  const colors = new Set<string>();
  for (const p of m.parts) {
    // Bounds of the voxels actually filled (grids can have empty margins). Eyelids are hidden
    // except in a blink, so they don't count towards its size.
    const g = p.grid;
    if (p.anim !== "lid") for (let y = 0; y < g.h; y++)
      for (let z = 0; z < g.d; z++)
        for (let x = 0; x < g.w; x++) {
          if (!g.data[(y * g.d + z) * g.w + x]) continue;
          const wx = p.origin[0] + x, wy = p.origin[1] + y, wz = p.origin[2] + z;
          if (wx < minX) minX = wx; if (wx + 1 > maxX) maxX = wx + 1;
          if (wy < minY) minY = wy; if (wy + 1 > maxY) maxY = wy + 1;
          if (wz < minZ) minZ = wz; if (wz + 1 > maxZ) maxZ = wz + 1;
        }
    tris += greedyMesh(p.grid).quads * 2;
    voxels += p.grid.count();
    const used = new Set(p.grid.data);
    for (const i of used) if (i) colors.add(p.grid.palette[i]);
  }
  const s = m.voxelSize;
  return { size: [(maxX - minX) * s, (maxY - minY) * s, (maxZ - minZ) * s], triangles: tris, voxels, colors: [...colors] };
}
